### ISSUE TITLE
Document link ends with 403 error

### ISSUE THREAD

**Issue by NamelessCoder** [TYPO3-Initiatives/structured-content#6]
The link to https://drive.google.com/drive/folders/0AIYK_5_L6LjgUk9PVA which is found in the README file results in a 403 error from Google Drive.

Please consider publishing that document as part of this repository instead.

**Comment by Bunnyfield** [comment]
Wokrs on my machine - maybe this is a permission problem and someone<TM> should change that.

**Comment by NamelessCoder** [comment]
![Screenshot 2020-02-11 at 12 25 29](https://user-images.githubusercontent.com/2228052/74232696-9dee5080-4cc9-11ea-936e-c19131000818.png)

Indeed looks like a permission issue. I'm guessing the document should be public?

**Comment by rfoucard** [comment]
Well, it's a link to the whole Initiative folder, so I think that kind of folder are limited to Initiative members only?

**Comment by Bunnyfield** [comment]
I don't know if it's a good idea to keep things secret behind closed doors. Especially when there are people who want to contribute, this might drive them away.

**Comment by ohader** [comment]
> Please consider publishing that document as part of this repository instead.

This link points to a directory in Google Drive (which however does not trigger a "request access" view). Thus, it's not just one document - but a bunch of sorted and some unsorted collections (including screenshots).

Technically making things public would be possible, however I suggest to first sort out documents that are supposed to be public due to privacy reasons (e.g. screenshots might contain public information, identifiers, system internal information).

@NamelessCoder My suggestion is to request access in the dedicated Slack channel by telling your Google ID. Besides that, are there any special documents or aspects you're interested in?

**Comment by NamelessCoder** [comment]
I've gained access now @ohader - though it required an access grant from the team. I can access it from the "shared with me" folder in Google Drive. I'll sift through it now, no need to bother you with requests for specific docs ;)
